<a href="https://colab.research.google.com/github/prakhar-luke/pytorch_practice/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.0.1+cu118'

In [2]:
import numpy as np

# Intro to Tensors

## Creating Tensors

### Scalar Tensor

In [ ]:
# Scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

### Vector

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

### Matrix

In [ ]:
# Matrix
Matrix = torch.tensor([[7,5],
                       [8,4]])
Matrix

tensor([[7, 5],
        [8, 4]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[0]

tensor([7, 5])

In [ ]:
Matrix.shape

torch.Size([2, 2])

### Tensor

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
Tensor[0][0][0]

tensor(1)

### Random Tensor

In [ ]:
# randome tensor
random_tensor = torch.rand(size=(3, 4))

In [ ]:
print(random_tensor)
print(random_tensor.dtype)
print(random_tensor.shape)
print(random_tensor.ndim)

tensor([[0.7558, 0.0915, 0.4734, 0.9220],
        [0.1478, 0.6913, 0.9425, 0.4875],
        [0.6458, 0.5920, 0.3301, 0.5753]])
torch.float32
torch.Size([3, 4])
2


In [ ]:
# create random tensor with simialr shape to an image tensor
rand_img_size_tensor = torch.rand(size=(224,224,3))
print(rand_img_size_tensor.shape)
print(rand_img_size_tensor.ndim)

torch.Size([224, 224, 3])
3


### Zeros and Ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
# Create a tensor of all ones
Ones = torch.ones(size=(3,2))
print(Ones)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
Ones.dtype

torch.float32

### Creating a range or tensors and tensors-like

In [ ]:
# Dont use torch.range(): torch.range() is deprecated and may show an error in the future.
one_2_end = torch.arange(start= 1, end= 11, step=2)
print(one_2_end)

tensor([1, 3, 5, 7, 9])


In [ ]:
# creating tensors like
one_2_nine = torch.zeros_like(one_2_end)
one_2_nine

tensor([0, 0, 0, 0, 0])

## Tensor DataTypes

Common datatype errors:
1. Tensors not right dtype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 4, 5],
                               dtype=None,            # datatype of tensor
                               device = None,         # where tensor is 'cpu' or 'cuda'
                               requires_grad=False)   # whether or to track gradient with this tensor operations

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16) # or torch.half

In [ ]:
float_16_tensor.dtype

torch.float16

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 16., 25.])

In [ ]:
int_bit32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)

## Getting information from tensors attributes

1. Tensors not right dtype - to get data type use `tensor.dtype`
2. Tensors not right shape - to get shape use `tensor.shape`
3. Tensors not on the right device - to get device use `tensor.device`

In [ ]:
rand_tensor = torch.rand(size=(3,2))
rand_tensor

tensor([[0.7240, 0.5078],
        [0.5549, 0.0397],
        [0.5720, 0.0166]])

In [ ]:
# finding details from tensor
print(rand_tensor)
print(f"DataType = {rand_tensor.dtype}")
print(f"Shape = {rand_tensor.shape}")
print(f"Device = {rand_tensor.device}")

tensor([[0.7240, 0.5078],
        [0.5549, 0.0397],
        [0.5720, 0.0166]])
DataType = torch.float32
Shape = torch.Size([3, 2])
Device = cpu


## Manipulating tensors

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
# create a tensor
tensor = torch.tensor([1, 2, 3])

### Addition

In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Subtract

In [ ]:
tensor - 10

tensor([-9, -8, -7])

In [ ]:
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

### Multiply

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Element wise multiplication

In [ ]:
print(tensor , "*", tensor)
print(f" = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
 = tensor([1, 4, 9])


Matrix Mul
(dot product)
- use `torch.matmul()` or `torch.mm()`
- inner dimension should match
- result shape = outer dimension

In [ ]:
torch.matmul(tensor,  tensor)

tensor(14)

In [ ]:
tensor1 = torch.rand(size=(3,2))
print(f"TENSOR 1 = {tensor1}, SIZE = {tensor1.shape}")
tensor2 = torch.rand(size=(3,2))
print(f"TENSOR 2 = {tensor2}, SIZE = {tensor2.shape}")

TENSOR 1 = tensor([[0.0408, 0.8899],
        [0.2656, 0.0217],
        [0.4556, 0.6591]]), SIZE = torch.Size([3, 2])
TENSOR 2 = tensor([[0.0834, 0.9965],
        [0.6408, 0.7315],
        [0.7961, 0.7251]]), SIZE = torch.Size([3, 2])


In [ ]:
# error cause inner dimension don't match
torch.matmul(tensor1, tensor2)

Transpose a tensor (use `.T` )

In [ ]:
tensor2.T, tensor2.T.shape

(tensor([[0.2249, 0.5378, 0.0890],
         [0.1749, 0.3781, 0.1282]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor1, tensor2.T)

tensor([[0.1937, 0.4429, 0.1063],
        [0.1888, 0.4190, 0.1225],
        [0.1625, 0.3716, 0.0890]])

## Finiding min, max, mean, sum, etc

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find Min
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [ ]:
# Find Max
x.max(), torch.max(x)

(tensor(90), tensor(90))

In [ ]:
# Find Mean (torach.mean() require tensor of float32 dtype)
x.type(torch.float32).mean(), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find Sum
x.sum(), torch.sum(x)

(tensor(450), tensor(450))

## Positional Min/Max

In [ ]:
# create a tensor
tensor = torch.arange(0, 100, 10)
print(f"Tensor : {tensor}")

# return index of Min, Max
print(f"Index of Min : {tensor.argmin()}")
print(f"Index of Max : {tensor.argmax()}")

Tensor : tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Index of Min : 0
Index of Max : 9


## Reshaping, stacking, squeezing, unsqueezing tensors

- reshape = reshapes an input tensor to a defined shape
- view = return a view of input tensor of cerain shape but keeps the same memory as the original tensor
- stacking - concat squence of ternsor along new dimension `(vstack, hstack)` also available
- squeeze = removes all `1` dimensions from a tensor
- unsqueeze = add a `1` dimenstion to target tensor
- Permute = return a view of the input with dimension permuted (swapped) in a ceratin way

In [ ]:
# create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add extra dimension (reshape)
x_reshaped = x.reshape(3,3) # (1,9), (9,1)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# chaging z cahnges x (because both point to same memory)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tesnors on top of each other
x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
v_stack = torch.vstack((x, x))
v_stack

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
h_stack = torch.hstack((x, x))
h_stack

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# torch.squeeze() = removes all singel dimensions from tensor
a = torch.rand(size=(2,1,3))
print(f"Tensor size = {a.shape}")
a_squeezed = torch.squeeze(a)
print(f'Squeezed size = {a_squeezed.shape}')

Tensor size = torch.Size([2, 1, 3])
Squeezed size = torch.Size([2, 3])


In [ ]:
# torch.unsqueeze() = return new tensor with dimension of size one inserted at the specified postion
a_unsqueezez = torch.unsqueeze(a_squeezed,1)
print(f"Unsqueezed size = {a_unsqueezez.shape}")

Unsqueezed size = torch.Size([2, 1, 3])


In [ ]:
# torch.permute() = return view of original tensor with dimensino permuted
test_img = torch.rand(size=(224, 224, 3)) # [h, w, Channel]
print(f"IMG dim : {test_img.shape}")

# permute/rearrange tensor's axis/dim
alt_img = torch.permute(test_img, (2,0,1)) # [Channel, h, w]
print(f"Alt img dim : {alt_img.shape}")

IMG dim : torch.Size([224, 224, 3])
Alt img dim : torch.Size([3, 224, 224])


In [ ]:
# since permute use view, altering new img will alter original as well
print('BEFORE')
print(f"test val alt img : {alt_img[0, 0, 0]}")
print(f"test val org img : {test_img[0, 0, 0]}")

print("AFTER")
alt_img[0, 0, 0] = 1
print(f"test val alt img : {alt_img[0, 0, 0]}")
print(f"test val org img : {test_img[0, 0, 0]}")

BEFORE
test val alt img : 0.5624673962593079
test val org img : 0.5624673962593079
AFTER
test val alt img : 1.0
test val org img : 1.0


## Change tensor Datatype

to change datatype of tensor use `torch.Tensor.type(dtype-None)` where `dtype` parameter is the datatype you'd like to use

In [ ]:
# Create a tensor
tensor = torch.arange(0, 100, 10)
tensor.dtype

torch.int64

In [ ]:
tensor_float32 = tensor.type(torch.float32)
tensor_float32.dtype

torch.float32

## Indexing

In [ ]:
# create a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
print(f"1st square bracket: {x[0]}")
print(f"2nd square bracket: {x[0][0]}")
print(f"3rd square bracket: {x[0][0][0]}")

1st square bracket: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2nd square bracket: tensor([1, 2, 3])
3rd square bracket: 1


In [ ]:
x[:, 0, 0]

tensor([1])

## PyTorch tensors & NumPy

- numpy-array to pytorch-tensor `torch.from_numpy(ndarray)`
- pytorch-tensor to numpy-array `torch.Tensor.numpy()`

In [5]:
# NumPy to Tensor
arr = np.arange(1., 8.)
# when converting from numpy -> pytorch, pytorch reflect numpy default dype (float64) insted of tensor defatult (float32)
# use `.type(torch.float64)` to change dtype
tensor = torch.from_numpy(arr)
arr, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [11]:
# Tensor to NumPy
tensor = torch.ones(7)
# when converting from pytorch -> numpy, tensor defatult (float32) is converted
# use `.astype('float64')` to change dtype
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (removing randomness)

In [13]:
rand_tensor1 = torch.rand(3,4)
rand_tensor2 = torch.rand(3,4)
print(f"TENSOR 1 : {rand_tensor1}")
print(f"TENSOR 2 : {rand_tensor2}")
rand_tensor1 == rand_tensor2

TENSOR 1 : tensor([[0.3102, 0.6571, 0.6645, 0.3201],
        [0.3029, 0.7793, 0.4945, 0.2251],
        [0.5848, 0.9696, 0.0385, 0.4143]])
TENSOR 2 : tensor([[0.6848, 0.7071, 0.5811, 0.3883],
        [0.5809, 0.7926, 0.4386, 0.8278],
        [0.7402, 0.6084, 0.1933, 0.2618]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
import torch
import random

# set random seed
RANDOM_SEED = 42

torch.manual_seed(seed=RANDOM_SEED)
rand_tensorA = torch.rand(3,4)

# have to reset the seed everytime a new rand() is called
torch.manual_seed(seed=RANDOM_SEED)
rand_tensorB = torch.rand(3,4)

print(f"TENSOR 1 : {rand_tensorA}")
print(f"TENSOR 2 : {rand_tensorB}")
print(rand_tensorA == rand_tensorB)

TENSOR 1 : tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
TENSOR 2 : tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensor on GPU

In [1]:
!nvidia-smi

Sat Sep 30 18:07:50 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   51C    P8    12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### Check for GPU

In [9]:
# Check for GPU
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1


### Setup device agnostic code

In [6]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

### Putting tensors (and models) on the GPU
 - use `.to(target_devie)`

In [12]:
# create a tensor
tensor = torch.tensor([1, 2, 3])

# tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [13]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

Notice the second tensor has device=`cuda:0`, this means it's stored on the 0th GPU available (GPUs are 0 indexed, if two GPUs were available, they'd be `cuda:0` and 'cuda:1' respectively, up to `cuda:n`).

### Moving back to CPU

In [14]:
# if tensor is on GPU, can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

Use `Tensor.cpu()` to copy the tensor to host memory first.

In [15]:
# insted, copy the tensor back to cpu
tensor_back_on_cpu = tensor.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])