<a href="https://colab.research.google.com/github/prakhar-luke/pytorch_practice/blob/main/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.1882, 0.1533, 0.9755, 0.0876, 0.0049, 0.2966, 0.3069],
        [0.5301, 0.0430, 0.1820, 0.8420, 0.0852, 0.4669, 0.0768],
        [0.1669, 0.6797, 0.1687, 0.6706, 0.8356, 0.4157, 0.3059],
        [0.8924, 0.1114, 0.5996, 0.6430, 0.7686, 0.3888, 0.2059],
        [0.9769, 0.9919, 0.8504, 0.9578, 0.8118, 0.5630, 0.6578],
        [0.4428, 0.7338, 0.6082, 0.5462, 0.4182, 0.4450, 0.3589],
        [0.6727, 0.7042, 0.6661, 0.9587, 0.0977, 0.9583, 0.1686]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor
rand_tensor2 = torch.rand(1,7)
# Perform matrix multiplication
torch.matmul(rand_tensor, rand_tensor2.T)
# torch.mm(rand_tensor, rand_tensor2.T)

tensor([[0.7644],
        [0.9578],
        [1.1240],
        [1.2732],
        [2.0487],
        [1.2865],
        [1.7062]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors
torch.manual_seed(seed=RANDOM_SEED)
rand_TensorA = torch.rand(7,7)
torch.manual_seed(seed=RANDOM_SEED)
rand_TensorB = torch.rand(1,7)

# Matrix multiply tensors
torch.matmul(rand_TensorA, rand_TensorB.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [3]:
import torch
# set device
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(seed=RANDOM_SEED)
rand_TensorA = torch.rand(size=(7,7), device=device)
print(rand_TensorA.device)

cuda:0



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [1]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [6]:
# Set random seed
RANDOM_SEED = 1234

# Check for access to GPU
print(device)

# Create two random tensors on GPU
# torch.cuda.manual_seed(seed=RANDOM_SEED)
torch.manual_seed(seed=RANDOM_SEED)
rand_T1 = torch.rand(size=(2,3), device=device)
rand_T2 = torch.rand(size=(2,3), device=device)
print(rand_T1.device, rand_T2.device)

cuda
cuda:0 cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
mul_tensor = torch.mm(rand_T1, rand_T1.T)
mul_tensor, mul_tensor.shape

(tensor([[0.9792, 0.8358],
         [0.8358, 1.4578]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
MaX = torch.max(mul_tensor)
# Find min
MiN = torch.min(mul_tensor)

print(MaX, MiN)

tensor(1.4578, device='cuda:0') tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
Max_idx = torch.argmax(mul_tensor)
print(Max_idx)
# Find arg min
Min_idx = torch.argmin(mul_tensor)
print(Min_idx)

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [19]:
# Set seed
RANDOM_SEED = 10

# Create random tensor
torch.manual_seed(seed=RANDOM_SEED)
tensor1 = torch.rand(size=(1,1,1,10))

# Remove single dimensions
dim_removed = tensor1.squeeze()
# Print out tensors and their shapes
print(f"TENSOR 1 : {tensor1} /n Shape : {tensor1.shape}")
print(f"TENSOR alt : {dim_removed} /n Shape : {dim_removed.shape}")

TENSOR 1 : tensor([[[[0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693,
           0.6178, 0.3304]]]]) /n Shape : torch.Size([1, 1, 1, 10])
TENSOR alt : tensor([0.4581, 0.4829, 0.3125, 0.6150, 0.2139, 0.4118, 0.6938, 0.9693, 0.6178,
        0.3304]) /n Shape : torch.Size([10])
